save_dir: ./saved_models
save_name: marginmatch_mini-imagenet_resnet12_npc100
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
# num_train_iter: 1048576
num_train_iter: 1048576
num_eval_iter: 1000
num_labels: 100
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net: resnet12
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
dropout: 0.0
data_dir: ./EP_data
dataset: mini-imagenet
train_sampler: RandomSampler
num_classes: 64
num_workers: 8
alg: marginmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: 0
delta: 0.997
use_threshold_examples: True
threshold_frequency_calculation_steps: 200
percentile: 95
switcher_frequency: 50000
warmup_period: 80000
delay: 1000
num_per_class: 100
