save_dir: ./saved_models
save_name: flexmatch_imagenet_128k_1
resume: False
load_path: None
overwrite: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 10000
num_labels: 128000
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.7
ulb_loss_ratio: 10
uratio: 5
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
amp: False
net: ResNet50
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 1
alg: flexmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10004
dist_backend: nccl
gpu: None
