save_dir: ./saved_models
resume: False
load_path: None
overwrite: True
epoch: 1
num_train_iter: 400000
num_eval_iter: 1000
num_labels: 1280
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
dropout: 0.0
train_sampler: RandomSampler
num_workers: 1
alg: flexmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10002
dist_backend: nccl
gpu: None
num_per_class: 20
save_name: flexmatch_mini-imagenet_conv4_npc020
data_dir: ../EP-semi/data
dataset: mini-imagenet
num_classes: 64
net: conv4